name: Export Public Sheet as HTML ZIP Stream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs dayly

jobs:
  export-sheet-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip tool
        run: sudo apt-get update && sudo apt-get install -y unzip curl

      - name: Stream-download and extract ZIP to root
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1Q8rcMCQEyQKiP3ftWzHH5hDotA35iqVaujgHnFIHDQM/export?format=zip" -o - | unzip -o -d .

      - name: Commit & push extracted files
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            DATE_STAMP=$(date +"%A %d/%m/%y - %I:%M %p")
            git add .
            git commit -m "Auto-update: $DATE_STAMP" || echo "No changes"
            git push
