name: Auto-update

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # - cron: "*/30 17-23 * * *"
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  export-exract-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip tool
        run: sudo apt-get update && sudo apt-get install -y unzip curl

      - name: Download and extract ZIP to root
        run: |
          mkdir -p temp_zip
          ZIP_FILE="temp_zip/sheet.zip"
          curl -L "https://docs.google.com/spreadsheets/d/1Q8rcMCQEyQKiP3ftWzHH5hDotA35iqVaujgHnFIHDQM/export?format=zip" -o $ZIP_FILE
          unzip -o $ZIP_FILE -d .
          rm -f $ZIP_FILE

      - name: Commit & push extracted files
        run: |
          DATE_STAMP=$(date +"%A %d/%m/%y - %I:%M %p")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update: $DATE_STAMP" || echo "No changes"
          git push
